// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// TeamsAPIService is a service that implements the logic for the TeamsAPIServicer
// This service should implement the business logic for every endpoint for the TeamsAPI API.
// Include any external packages or services that will be required by this service.
type TeamsAPIService struct {
}

// NewTeamsAPIService creates a default api service
func NewTeamsAPIService() TeamsAPIServicer {
	return &TeamsAPIService{}
}

// CreateTeam - Create a new team for an organization
func (s *TeamsAPIService) CreateTeam(ctx context.Context, orgId string, teamInput TeamInput) (ImplResponse, error) {
	// TODO - update CreateTeam with the required logic for this service method.
	// Add api_teams_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Team{}) or use other options such as http.Ok ...
	// return Response(201, Team{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTeam method not implemented")
}

// DeleteTeam - Delete a specific team
func (s *TeamsAPIService) DeleteTeam(ctx context.Context, orgId string, teamId string) (ImplResponse, error) {
	// TODO - update DeleteTeam with the required logic for this service method.
	// Add api_teams_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTeam method not implemented")
}

// GetTeam - Get a specific team by ID
func (s *TeamsAPIService) GetTeam(ctx context.Context, orgId string, teamId string) (ImplResponse, error) {
	// TODO - update GetTeam with the required logic for this service method.
	// Add api_teams_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Team{}) or use other options such as http.Ok ...
	// return Response(200, Team{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTeam method not implemented")
}

// ListTeams - List all teams in an organization
func (s *TeamsAPIService) ListTeams(ctx context.Context, orgId string) (ImplResponse, error) {
	// TODO - update ListTeams with the required logic for this service method.
	// Add api_teams_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Team{}) or use other options such as http.Ok ...
	// return Response(200, []Team{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListTeams method not implemented")
}

// UpdateTeam - Update a specific team
func (s *TeamsAPIService) UpdateTeam(ctx context.Context, orgId string, teamId string, teamInput TeamInput) (ImplResponse, error) {
	// TODO - update UpdateTeam with the required logic for this service method.
	// Add api_teams_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Team{}) or use other options such as http.Ok ...
	// return Response(200, Team{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateTeam method not implemented")
}
