// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DraftsAPIService is a service that implements the logic for the DraftsAPIServicer
// This service should implement the business logic for every endpoint for the DraftsAPI API.
// Include any external packages or services that will be required by this service.
type DraftsAPIService struct {
}

// NewDraftsAPIService creates a default api service
func NewDraftsAPIService() DraftsAPIServicer {
	return &DraftsAPIService{}
}

// CreatePromptDraft - Create a new draft for a prompt
func (s *DraftsAPIService) CreatePromptDraft(ctx context.Context, promptId string, promptDraftInput PromptDraftInput) (ImplResponse, error) {
	// TODO - update CreatePromptDraft with the required logic for this service method.
	// Add api_drafts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, PromptDraft{}) or use other options such as http.Ok ...
	// return Response(201, PromptDraft{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreatePromptDraft method not implemented")
}

// ListPromptDrafts - List all drafts of a specific prompt
func (s *DraftsAPIService) ListPromptDrafts(ctx context.Context, promptId string) (ImplResponse, error) {
	// TODO - update ListPromptDrafts with the required logic for this service method.
	// Add api_drafts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []PromptDraft{}) or use other options such as http.Ok ...
	// return Response(200, []PromptDraft{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListPromptDrafts method not implemented")
}

// MergeDraftIntoVersion - Merge an approved draft into a new version
func (s *DraftsAPIService) MergeDraftIntoVersion(ctx context.Context, promptId string, draftId string) (ImplResponse, error) {
	// TODO - update MergeDraftIntoVersion with the required logic for this service method.
	// Add api_drafts_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("MergeDraftIntoVersion method not implemented")
}
