// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// HealthCheckAPIService is a service that implements the logic for the HealthCheckAPIServicer
// This service should implement the business logic for every endpoint for the HealthCheckAPI API.
// Include any external packages or services that will be required by this service.
type HealthCheckAPIService struct {
}

// NewHealthCheckAPIService creates a default api service
func NewHealthCheckAPIService() HealthCheckAPIServicer {
	return &HealthCheckAPIService{}
}

// HealthCheck - Health Check Endpoint
func (s *HealthCheckAPIService) HealthCheck(ctx context.Context) (ImplResponse, error) {
	// TODO - update HealthCheck with the required logic for this service method.
	// Add api_health_check_service.pkg to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, HealthCheck200Response{}) or use other options such as http.Ok ...
	// return Response(200, HealthCheck200Response{}), nil

	// TODO: Uncomment the next line to return response Response(500, HealthCheck500Response{}) or use other options such as http.Ok ...
	// return Response(500, HealthCheck500Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("HealthCheck method not implemented")
}
