// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// ApprovalsAPIService is a service that implements the logic for the ApprovalsAPIServicer
// This service should implement the business logic for every endpoint for the ApprovalsAPI API.
// Include any external packages or services that will be required by this service.
type ApprovalsAPIService struct {
}

// NewApprovalsAPIService creates a default api service
func NewApprovalsAPIService() ApprovalsAPIServicer {
	return &ApprovalsAPIService{}
}

// AddApprovalToDraft - Add an approval to a draft
func (s *ApprovalsAPIService) AddApprovalToDraft(ctx context.Context, promptId string, draftId string, body map[string]interface{}) (ImplResponse, error) {
	// TODO - update AddApprovalToDraft with the required logic for this service method.
	// Add api_approvals_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddApprovalToDraft method not implemented")
}

// ListApprovalsOnDraft - List all approvals on a draft
func (s *ApprovalsAPIService) ListApprovalsOnDraft(ctx context.Context, promptId string, draftId string) (ImplResponse, error) {
	// TODO - update ListApprovalsOnDraft with the required logic for this service method.
	// Add api_approvals_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Approval{}) or use other options such as http.Ok ...
	// return Response(200, []Approval{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListApprovalsOnDraft method not implemented")
}

// RemoveApprovalFromDraft - Remove an approval from a draft
func (s *ApprovalsAPIService) RemoveApprovalFromDraft(ctx context.Context, promptId string, draftId string) (ImplResponse, error) {
	// TODO - update RemoveApprovalFromDraft with the required logic for this service method.
	// Add api_approvals_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("RemoveApprovalFromDraft method not implemented")
}
