// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CommentsAPIService is a service that implements the logic for the CommentsAPIServicer
// This service should implement the business logic for every endpoint for the CommentsAPI API.
// Include any external packages or services that will be required by this service.
type CommentsAPIService struct {
}

// NewCommentsAPIService creates a default api service
func NewCommentsAPIService() CommentsAPIServicer {
	return &CommentsAPIService{}
}

// AddCommentToDraft - Add a comment to a draft
func (s *CommentsAPIService) AddCommentToDraft(ctx context.Context, promptId string, draftId string, commentInput CommentInput) (ImplResponse, error) {
	// TODO - update AddCommentToDraft with the required logic for this service method.
	// Add api_comments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
	// return Response(201, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddCommentToDraft method not implemented")
}

// DeleteCommentFromDraft - Delete a comment from a draft
func (s *CommentsAPIService) DeleteCommentFromDraft(ctx context.Context, promptId string, draftId string, commentId string) (ImplResponse, error) {
	// TODO - update DeleteCommentFromDraft with the required logic for this service method.
	// Add api_comments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteCommentFromDraft method not implemented")
}

// ListCommentsOnDraft - List all comments on a draft
func (s *CommentsAPIService) ListCommentsOnDraft(ctx context.Context, promptId string, draftId string) (ImplResponse, error) {
	// TODO - update ListCommentsOnDraft with the required logic for this service method.
	// Add api_comments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Comment{}) or use other options such as http.Ok ...
	// return Response(200, []Comment{}), nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListCommentsOnDraft method not implemented")
}

// UpdateCommentOnDraft - Update a comment on a draft
func (s *CommentsAPIService) UpdateCommentOnDraft(ctx context.Context, promptId string, draftId string, commentId string, commentInput CommentInput) (ImplResponse, error) {
	// TODO - update UpdateCommentOnDraft with the required logic for this service method.
	// Add api_comments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateCommentOnDraft method not implemented")
}
