// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi




type PromptDraftInput struct {

	// Name of the draft
	Name string `json:"name"`

	// A brief description of the project
	Description string `json:"description,omitempty"`

	// Content of the draft
	Content string `json:"content"`
}

// AssertPromptDraftInputRequired checks if the required fields are not zero-ed
func AssertPromptDraftInputRequired(obj PromptDraftInput) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"content": obj.Content,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPromptDraftInputConstraints checks if the values respects the defined constraints
func AssertPromptDraftInputConstraints(obj PromptDraftInput) error {
	return nil
}
