// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi


import (
	"time"
)



type Comment struct {

	// Unique identifier for the comment
	Id string `json:"id,omitempty"`

	// User ID of the author of the comment
	UserId string `json:"userId,omitempty"`

	// Text content of the comment
	Text string `json:"text,omitempty"`

	// Optional reference to a specific line in the draft content
	LineNumber int32 `json:"lineNumber,omitempty"`

	// Timestamp when the comment was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Timestamp when the comment was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertCommentRequired checks if the required fields are not zero-ed
func AssertCommentRequired(obj Comment) error {
	return nil
}

// AssertCommentConstraints checks if the values respects the defined constraints
func AssertCommentConstraints(obj Comment) error {
	return nil
}
