// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi




type HealthCheck200ResponseDetails struct {

	Database string `json:"database,omitempty"`

	// Time in milliseconds that the API has been operational, indicating stability and reliability.
	Uptime float64 `json:"uptime,omitempty"`
}

// AssertHealthCheck200ResponseDetailsRequired checks if the required fields are not zero-ed
func AssertHealthCheck200ResponseDetailsRequired(obj HealthCheck200ResponseDetails) error {
	return nil
}

// AssertHealthCheck200ResponseDetailsConstraints checks if the values respects the defined constraints
func AssertHealthCheck200ResponseDetailsConstraints(obj HealthCheck200ResponseDetails) error {
	return nil
}
