// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi




type CommentInput struct {

	// Text content of the comment
	Text string `json:"text"`

	// Optional reference to a specific line in the draft content
	LineNumber int32 `json:"lineNumber,omitempty"`
}

// AssertCommentInputRequired checks if the required fields are not zero-ed
func AssertCommentInputRequired(obj CommentInput) error {
	elements := map[string]interface{}{
		"text": obj.Text,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCommentInputConstraints checks if the values respects the defined constraints
func AssertCommentInputConstraints(obj CommentInput) error {
	return nil
}
