// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi


import (
	"time"
)



type Approval struct {

	// User ID of the person who approved the draft
	UserId string `json:"userId,omitempty"`

	// Timestamp when the approval was given
	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// AssertApprovalRequired checks if the required fields are not zero-ed
func AssertApprovalRequired(obj Approval) error {
	return nil
}

// AssertApprovalConstraints checks if the values respects the defined constraints
func AssertApprovalConstraints(obj Approval) error {
	return nil
}
