// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi


import (
	"time"
)



type PromptVersion struct {

	// Unique identifier for the version of the prompt
	Id string `json:"id,omitempty"`

	// Content of the prompt at this version
	Content string `json:"content,omitempty"`

	// Identifier of the prompt this version belongs to
	PromptId string `json:"promptId,omitempty"`

	// Timestamp when this version was created
	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// AssertPromptVersionRequired checks if the required fields are not zero-ed
func AssertPromptVersionRequired(obj PromptVersion) error {
	return nil
}

// AssertPromptVersionConstraints checks if the values respects the defined constraints
func AssertPromptVersionConstraints(obj PromptVersion) error {
	return nil
}
