# Start from the official Golang image to build the binary.
FROM golang:1.20 as builder
WORKDIR /app
COPY . .
RUN go build -o app

# Use a smaller image to run the app
FROM alpine:latest  
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/app .
CMD ["./app"]
