version: '3.9'

services:
  platoapi:
    container_name: "lanyardapi"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - JWT_SECRET=test
      - BIND_ADDRESS=:8080
      - ENVIRONMENT=local
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - PROMPT_BUCKET=local-api.payloadops.com
    depends_on:
      - localstack
      - otel-collector
    ports:
      - "8080:8080"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock

  otel-collector:
    container_name: "otel-collector"
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    ports:
      - "4317:4317"  # OTLP gRPC receiver
    volumes:
      - type: bind
        source: ./otlp-config.yaml
        target: /etc/otlp-config.yaml
    command: [ "--config=/etc/otlp-config.yaml" ]