// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type OrganizationInput struct {

	// Name of the organization
	Name string `json:"name"`

	// Description for the organization
	Description string `json:"description,omitempty"`
}

// AssertOrganizationInputRequired checks if the required fields are not zero-ed
func AssertOrganizationInputRequired(obj OrganizationInput) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertOrganizationInputConstraints checks if the values respects the defined constraints
func AssertOrganizationInputConstraints(obj OrganizationInput) error {
	return nil
}
