// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lanyard Ops API
 *
 * The Lanyard Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type Actor struct {

	// Unique identifier for the API key
	ExternalId string `json:"externalId,omitempty"`

	// Billing info for actor
	BillingInfo BillingInfo `json:"billingInfo,omitempty"`

	// Number of monthly requests
	MonthlyRequestLimit int32 `json:"monthlyRequestLimit,omitempty"`
}

// AssertActorRequired checks if the required fields are not zero-ed
func AssertActorRequired(obj Actor) error {
	if err := AssertBillingInfoRequired(obj.BillingInfo); err != nil {
		return err
	}
	return nil
}

// AssertActorConstraints checks if the values respects the defined constraints
func AssertActorConstraints(obj Actor) error {
	return nil
}
