// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"time"
)

type TestCase struct {

	// Unique identifier for the test case of the branch
	Id string `json:"id,omitempty"`

	// Name of this test case
	Name string `json:"name,omitempty"`

	// Content of the parameters in this test case
	Parameters []TestCaseParameter `json:"parameters,omitempty"`

	// Timestamp when this test case was updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`

	// Timestamp when this test case was created
	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// AssertTestCaseRequired checks if the required fields are not zero-ed
func AssertTestCaseRequired(obj TestCase) error {
	for _, el := range obj.Parameters {
		if err := AssertTestCaseParameterRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTestCaseConstraints checks if the values respects the defined constraints
func AssertTestCaseConstraints(obj TestCase) error {
	return nil
}
