// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lanyard Ops API
 *
 * The Lanyard Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

// PricingTier - Represents a pricing tier for API usage, defining limits and features associated with the service.
type PricingTier struct {

	// Unique identifier for the pricing tier
	Id string `json:"id,omitempty"`

	// The name of the pricing tier (e.g., Free, Pro, Enterprise)
	Name string `json:"name,omitempty"`

	// The maximum number of API requests allowed per month
	DefaultMonthlyRequestLimit int32 `json:"defaultMonthlyRequestLimit,omitempty"`

	// Rate limit configuration for the tier (requests per second or minute)
	DefaultRateLimit RateLimit `json:"defaultRateLimit,omitempty"`

	// The price per extra request beyond the monthly limit
	OveragePrice float32 `json:"overagePrice,omitempty"`
}

// AssertPricingTierRequired checks if the required fields are not zero-ed
func AssertPricingTierRequired(obj PricingTier) error {
	if err := AssertRateLimitRequired(obj.DefaultRateLimit); err != nil {
		return err
	}
	return nil
}

// AssertPricingTierConstraints checks if the values respects the defined constraints
func AssertPricingTierConstraints(obj PricingTier) error {
	return nil
}
