// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi




type UserInput struct {

	// User's full name (optional)
	Name string `json:"name,omitempty"`

	// User's email address
	Email string `json:"email"`
}

// AssertUserInputRequired checks if the required fields are not zero-ed
func AssertUserInputRequired(obj UserInput) error {
	elements := map[string]interface{}{
		"email": obj.Email,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserInputConstraints checks if the values respects the defined constraints
func AssertUserInputConstraints(obj UserInput) error {
	return nil
}
