// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"time"
)

// BillingInfo - Billing information, including pricing tier and trial expiration date
type BillingInfo struct {

	// Pricing tier of the API key
	Tier string `json:"tier,omitempty"`

	// ID of pricing tier
	TierId string `json:"tierId,omitempty"`

	// The date when the trial period ends
	TrialExpiry time.Time `json:"trialExpiry,omitempty"`

	// Indicates whether the trial period is currently active for this actor
	IsTrialActive bool `json:"isTrialActive,omitempty"`

	// Indicates whether the actor is eligble for a trial period
	IsTrialElgible bool `json:"isTrialElgible,omitempty"`
}

// AssertBillingInfoRequired checks if the required fields are not zero-ed
func AssertBillingInfoRequired(obj BillingInfo) error {
	return nil
}

// AssertBillingInfoConstraints checks if the values respects the defined constraints
func AssertBillingInfoConstraints(obj BillingInfo) error {
	return nil
}
