// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type TestCaseInput struct {

	// Name of this test case
	Name string `json:"name"`

	// List of parameters for this test case
	Parameters []TestCaseParameter `json:"parameters"`
}

// AssertTestCaseInputRequired checks if the required fields are not zero-ed
func AssertTestCaseInputRequired(obj TestCaseInput) error {
	elements := map[string]interface{}{
		"name":       obj.Name,
		"parameters": obj.Parameters,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Parameters {
		if err := AssertTestCaseParameterRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTestCaseInputConstraints checks if the values respects the defined constraints
func AssertTestCaseInputConstraints(obj TestCaseInput) error {
	return nil
}
