// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type ServicesServiceIdKeyKeyIdAuthPost200Response struct {
	Authorized bool `json:"authorized,omitempty"`

	Scopes []string `json:"scopes,omitempty"`
}

// AssertServicesServiceIdKeyKeyIdAuthPost200ResponseRequired checks if the required fields are not zero-ed
func AssertServicesServiceIdKeyKeyIdAuthPost200ResponseRequired(obj ServicesServiceIdKeyKeyIdAuthPost200Response) error {
	return nil
}

// AssertServicesServiceIdKeyKeyIdAuthPost200ResponseConstraints checks if the values respects the defined constraints
func AssertServicesServiceIdKeyKeyIdAuthPost200ResponseConstraints(obj ServicesServiceIdKeyKeyIdAuthPost200Response) error {
	return nil
}
