// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type ActorInput struct {

	// Unique identifier for the API key
	ExternalId string `json:"externalId,omitempty"`
}

// AssertActorInputRequired checks if the required fields are not zero-ed
func AssertActorInputRequired(obj ActorInput) error {
	return nil
}

// AssertActorInputConstraints checks if the values respects the defined constraints
func AssertActorInputConstraints(obj ActorInput) error {
	return nil
}
