// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Lanyard Ops API
 *
 * The Lanyard Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type HealthCheckSuccessResponse struct {
	Status string `json:"status,omitempty"`
}

// AssertHealthCheckSuccessResponseRequired checks if the required fields are not zero-ed
func AssertHealthCheckSuccessResponseRequired(obj HealthCheckSuccessResponse) error {
	return nil
}

// AssertHealthCheckSuccessResponseConstraints checks if the values respects the defined constraints
func AssertHealthCheckSuccessResponseConstraints(obj HealthCheckSuccessResponse) error {
	return nil
}
