// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API simplifies API key management for organizations by providing powerful tools to create, manage, and monitor API access securely. It allows teams to generate scoped API keys, configure rate limits, track usage, and integrate seamlessly with existing services.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

// RateLimitInput - Rate limit configuration for this API key
type RateLimitInput struct {

	// The name of the rate limit
	Name string `json:"name,omitempty"`

	// The number of allowed requests in the defined time window
	Limit int32 `json:"limit,omitempty"`

	// Time window for the rate limit, specified in ISO duration format (e.g., '1h', '30m')
	Window string `json:"window,omitempty"`
}

// AssertRateLimitInputRequired checks if the required fields are not zero-ed
func AssertRateLimitInputRequired(obj RateLimitInput) error {
	return nil
}

// AssertRateLimitInputConstraints checks if the values respects the defined constraints
func AssertRateLimitInputConstraints(obj RateLimitInput) error {
	return nil
}
