// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type BranchInput struct {

	// Branch name unique to the prompt
	Name string `json:"name,omitempty"`
}

// AssertBranchInputRequired checks if the required fields are not zero-ed
func AssertBranchInputRequired(obj BranchInput) error {
	return nil
}

// AssertBranchInputConstraints checks if the values respects the defined constraints
func AssertBranchInputConstraints(obj BranchInput) error {
	return nil
}
