// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"time"
)

type Project struct {

	// A K-sortable unique identifier (KSUID)
	Id string `json:"id,omitempty"`

	// Name of the project
	Name string `json:"name,omitempty"`

	// A brief description of the project
	Description string `json:"description,omitempty"`

	// A K-sortable unique identifier (KSUID)
	OrgId string `json:"orgId,omitempty"`

	// A K-sortable unique identifier (KSUID)
	TeamId string `json:"teamId,omitempty"`

	// Timestamp when the project was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Timestamp when the project was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertProjectRequired checks if the required fields are not zero-ed
func AssertProjectRequired(obj Project) error {
	return nil
}

// AssertProjectConstraints checks if the values respects the defined constraints
func AssertProjectConstraints(obj Project) error {
	return nil
}
