// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

type ApiKeyInput struct {

	// List of scopes or permissions to be granted to this API key
	Scopes []string `json:"scopes"`
}

// AssertApiKeyInputRequired checks if the required fields are not zero-ed
func AssertApiKeyInputRequired(obj ApiKeyInput) error {
	elements := map[string]interface{}{
		"scopes": obj.Scopes,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertApiKeyInputConstraints checks if the values respects the defined constraints
func AssertApiKeyInputConstraints(obj ApiKeyInput) error {
	return nil
}
