// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi

import (
	"time"
)

type Organization struct {

	// Unique identifier for the organization
	Id string `json:"id,omitempty"`

	// Name of the organization
	Name string `json:"name,omitempty"`

	// Description for the organization
	Description string `json:"description,omitempty"`

	// Timestamp of organization creation
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Timestamp of the last update to the organization
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertOrganizationRequired checks if the required fields are not zero-ed
func AssertOrganizationRequired(obj Organization) error {
	return nil
}

// AssertOrganizationConstraints checks if the values respects the defined constraints
func AssertOrganizationConstraints(obj Organization) error {
	return nil
}
