// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payload Ops API
 *
 * The Payload Ops API streamlines management of AI prompts, projects, organizations, teams, and users through conventional HTTP requests. This platform enables efficient automation and control of resources, providing robust tools for developers to manage settings, memberships, and activities seamlessly.
 *
 * API version: 1.0
 * Contact: info@payloadops.com
 */

package openapi


import (
	"time"
)



type ApiKey struct {

	// Unique identifier for the API key
	Id string `json:"id,omitempty"`

	// The API key token
	Key string `json:"key,omitempty"`

	// List of scopes or permissions granted by this API key
	Scopes []string `json:"scopes,omitempty"`

	// The project ID this API key belongs to
	ProjectId string `json:"projectId,omitempty"`

	// Timestamp when the API key was created
	CreatedAt time.Time `json:"createdAt,omitempty"`

	// Timestamp when the API key was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}

// AssertApiKeyRequired checks if the required fields are not zero-ed
func AssertApiKeyRequired(obj ApiKey) error {
	return nil
}

// AssertApiKeyConstraints checks if the values respects the defined constraints
func AssertApiKeyConstraints(obj ApiKey) error {
	return nil
}
