version: '3.9'

services:
  platoapi:
    container_name: "platoapi"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - JWT_SECRET=test
      - BIND_ADDRESS=:8080
      - ENVIRONMENT=local
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    ports:
      - "8080:8080"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack}"
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=dynamodb,s3
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
