name: Deploy CDK Stack

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Load AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets['AWS_ACCESS_KEY_ID_' + inputs.environment] }}
        aws-secret-access-key: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + inputs.environment] }}
        aws-region: 'us-east-1'  # Example region, customize as necessary

    - name: Install dependencies
      run: go mod tidy

    - name: Deploy to AWS
      run: cdk deploy --all --require-approval never
      env:
        ENV_NAME: ${{ github.event.inputs.environment }}
