name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * 1-4'  # At 01:00 on Monday to Thursday

jobs:
  build-test-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-openapi@v2
        with:
          go-version: '1.18'

      - name: Build packages and run unit tests
        run: |
          go build ./...
          go test ./...

      - name: Check for vulnerabilities
        run: echo "Run security scanning tools here"
  

  deploy-to-dev:
    needs: build-and-test
    uses: ./.github/workflows/stage-deploy.yml
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      environment: dev

  deploy-to-staging:
    needs: deploy-to-dev
    uses: ./.github/workflows/stage-deploy.yml
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
      aws-region: ${{ secrets.AWS_REGION_STAGING }}
      environment: staging

  delayed-production-deploy:
    needs: deploy-to-staging
    if: github.event_name == 'schedule' && fromJSON('["Mon","Tue","Wed","Thu"]').contains(format('{0:ddd}', github.event.schedule.*))
    uses: ./.github/workflows/stage-deploy.yml
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-region: ${{ secrets.AWS_REGION_PROD }}
      environment: production
